custom:
  config: ${file(./env.yml):${opt:stage}.config}
  env: ${file(./env.yml):${opt:stage}.env}

service: ${file(./services/${opt:service}/service.yml):service}

plugins:
  - serverless-offline
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.config.region}
  iamRoleStatements: ${file(./services/${opt:service}/service.yml):iamRoleStatements, ""}
  role: ${file(./services/${opt:service}/service.yml):role, ""}

package: ${file(./services/${opt:service}/service.yml):package}

functions: ${file(./services/${opt:service}/service.yml):functions}